Remove deprecated call to pkg_resources
glue-viz/echo pull request #36
Opened 2023-04-03 19:17 UTC by jfoster17

# Remove explicit calls to pkg_resources

## Description

Following the process in https://github.com/glue-viz/glue/pull/2365, this updates echo to not depend on the deprecated pkg_resources API, at the cost of requiring `importlib_metadata` for older versions of Python (but glue installations will have this dependency anyway with the above-referenced change).

2023-04-03 20:03 UTC, jfoster17 commented
I'm not sure exactly what's going on what that remaining test failure.

2023-04-03 21:43 UTC, dhomeier commented
> OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '--cov-report=xml:D:\\a\\echo\\echo\\coverage.xml'

I recall seeing that elsewhere with an older Windows env, obviously messing up the volume label in the default `--cov-report=xml:{toxinidir}/coverage.xml` or whatever it is; don't remember how that was fixed though (other than retiring Python 3.7 at least for the Windows test perhaps) – pyqt510 is quite old...

2023-04-04 10:17 UTC, astrofrog commented
Thanks! We've already dropped Python 3.7 for glue-core so I think we can just require >=3.8 here now?

2023-04-04 12:57 UTC, dhomeier commented
Was wondering if it was required for pyqt510, but 5.10.1 seems to have wheels for 3.8 already.

2023-04-04 13:10 UTC, jfoster17 commented
> Was wondering if it was required for pyqt510, but 5.10.1 seems to have wheels for 3.8 already.

Looks like I pushed just as you were commenting here. I removed the py37 tests, but do you want one back for pyqt510? The main glue package requires >=5.14, so we could just drop some older versions...

2023-04-04 13:21 UTC, dhomeier commented
Was just wondering if there was a specific reason to test the older versions here, but otherwise yes, keeping them in sync with glue-core (which underwent a major cleanup last year) probably makes sense.

2023-04-04 15:05 UTC, astrofrog commented
Keeping in sync with glue-core is fine!

2023-08-05 20:04 UTC, dhomeier requested changes
Added some suggestions for py311 test envs, will still need to be added to `tox.ini` – @jfoster17 we should re-run the CI with these, and then this should finally be ready to go.

2023-08-05 20:04 UTC, dhomeier commented on setup.cfg
> +    Programming Language :: Python :: 3.10
```suggestion
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
```

2023-08-11 19:40 UTC, dhomeier approved these changes

2023-08-11 19:41 UTC, dhomeier commented
Thanks, everything looking great! I will probably squash for the merge.

2023-08-11 19:44 UTC, jfoster17 commented
Okay, please do squash.

2023-08-11 19:54 UTC, dhomeier commented
Alternatively, if you could squash just the last 4 commits into one and force-push, should be good as well. But either way is fine.

2023-08-11 21:40 UTC, merged